### PR TITLE
change build your own to Interested in phaser games + add skillpath link

### PR DESCRIPTION
**Pull request by kailinwei**

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Hi @kailinwei, thanks for your interest in 40Phaser! This PR unfortunately looks a little bit like spam, as there is no issue asking for it and it's a small text change. Closing to keep our queue small.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

If you think this is a mistake, please respond here and I'd be happy to reopen!

**Comment by kailinwei** [comment]
Hello Josh,
  Thanks for your feedback. This is my first time using github, so glad to
get my first feedback. I apologize for not making the change as you wanted
this time. I will keep studying and improve in the future.
Have a nice day!
Kailin

**Comment by JoshuaKGoldberg** [comment]
No worries @kailinwei, welcome to the world of GitHub! 🙌 
I appreciate you messaging back very much.

In case it's helpful, many repositories (including this one) and maintainers (including me) prefer pull requests only be sent for something that's either:

* Definitely a very small typo (such as a common word being misspelled in a `.md` file or code comment
* Already filed as an issue on that repository's issue tracker _and_ marked with a label such as `accepting prs` or `status: accepting prs`.

If you're still interested, I'd still love to have a contribution from you on this repository. We have a [few issues](https://github.com/Codecademy/40Phaser/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+accepting+prs%22) accepting PRs right now; #65 is probably the best one to get started. No worries if you don't have the time to tackle it, but know that you're very welcome to! 🤗

**Comment by kailinwei** [comment]
Hi Josh,
  Thanks for your explanation and friendly invitation. I will see if I can
figure that out.
Have a good day,
Kailin

**Pull request closed without merging**
